/**
 * Dictionary Entry DTO
 * Matches the JSON structure generated by the DeepSeek LLM dictionary prompt.
 * See /public/字典.json for a concrete example.
 */
export interface DictEntryDTO {
  word: string;
  phonetics: {
    us: string;
    uk: string;
  };
  audio_urls: {
    us: string;
    uk: string;
  };
  inflections: {
    plural: string | null;
    past_tense: string | null;
    present_participle: string | null;
    third_person_singular: string | null;
    adjective_form: string | null;
  };
  definitions: Array<{
    pos: string;
    meaning_cn: string;
    meaning_en: string;
    cefr_level: string | null;
  }>;
  etymology: {
    prefix: string | null;
    root: string | null;
    suffix: string | null;
    breakdown: string;
    mnemonic: string;
  };
  phrases_and_collocations: Array<{
    phrase: string;
    meaning_cn: string;
  }>;
  synonyms: string[];
  antonyms: string[];
  examples: Array<{
    en: string;
    cn: string;
    context: string;
  }>;
}
